[tool.poetry]
name = "marinengpt-demo"
version = "0.1.0"
description = ""
authors = ["suprch4rg3d <emmanueloikonomou@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
clip = {git = "https://github.com/openai/CLIP.git"}
chainlit = "^1.3.2"
llama-index = "^0.12.8"
openai = "^1.58.1"
pymupdf = "^1.25.1"
ocrmypdf = "^16.7.0"
pydantic = "2.10.1"
llama-index-tools-weather = "^0.3.0"
llama-index-embeddings-clip = "^0.3.1"
pyperclip = "^1.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
