weather_keywords = [
    "Weather",
    "Forecast",
    "Temperature",
    "Rain",
    "Snow",
    "Sun",
    "Cloud",
    "Wind",
    "Humidity",
    "Storm",
    "Tornado",
    "Hurricane",
    "Cyclone",
    "Blizzard",
    "Thunderstorm",
    "Haze",
    "Fog",
    "Sleet",
    "Hail",
    "Drought",
    "Heatwave",
    "Feels like",
    "High",
    "Low",
    "Pressure",
    "Visibility",
    "UV index",
    "Sunrise",
    "Sunset",
    "Precipitation",
    "Chance of",
    "Windy",
    "Calm",
    "Breezy",
    "Humid",
    "Dry",
    "Clear",
    "Overcast",
    "Partly cloudy",
    "Stormy",
    "Tropical",
    "Arctic",
    "Gale",
    "Squall",
    "Flurry",
    "Drizzle",
    "Monsoon",
    "Sunny",
    "Raining",
    "Snowy",
    "Cloudy",
    "Stormy",
    "Windy",
    "Humid",
    "Dry",
    "Temperatures",
    "weather",
    "forecast",
    "temperature",
    "rain",
    "snow",
    "sun",
    "cloud",
    "wind",
    "humidity",
    "storm",
    "tornado",
    "hurricane",
    "cyclone",
    "blizzard",
    "thunderstorm",
    "haze",
    "fog",
    "sleet",
    "hail",
    "drought",
    "heatwave",
    "feels like",
    "high",
    "low",
    "pressure",
    "visibility",
    "UV index",
    "sunrise",
    "sunset",
    "precipitation",
    "windy",
    "calm",
    "breezy",
    "humid",
    "dry",
    "clear",
    "overcast",
    "partly cloudy",
    "stormy",
    "tropical",
    "arctic",
    "gale",
    "squall",
    "flurry",
    "drizzle",
    "monsoon",
    "sunny",
    "raining",
    "snowy",
    "cloudy",
    "stormy",
    "windy",
    "humid",
    "dry",
    "temperatures",
]

present_tense_keywords = ["today", "now", "current", "is", "tonight"]
future_tense_keywords = ["tomorrow", "will"]

def detect_tense_simple(message):
  for keyword in present_tense_keywords:
    if keyword.lower() in message.lower():
      return "PRES"
  for keyword in future_tense_keywords:
    if keyword.lower() in message.lower():
      return "FUT"
  return None